# Generated by Django 3.1.7 on 2021-04-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auth',
            name='user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auth',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
